
# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=y

CONFIG_EEPROM=y
CONFIG_FRAM_FM24CL64B=y 
CONFIG_RADIO_CC1125=y
CONFIG_BATP_BQ76907=y