
# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=y

CONFIG_FRAM_FM24CL64B=y 

CONFIG_BATP_BQ76907=y

CONFIG_IEEE802154_CC1200=y

CONFIG_TMP112=y
CONFIG_BMP388=y
CONFIG_INA219=y
CONFIG_LSM9DS1=y
CONFIG_RTC_RV8803=y